### ISSUE TITLE
Cant read input file

### ISSUE THREAD

**Issue by Leastrio** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#34]
Getting this error when trying to run the jar
```
PS C:\Users\craft\Desktop\Amongus> java -jar .\Among-Us-Dumpy-Gif-Maker-3.1.3-all.jar --file .\Bot-Logo.png
1
3
0
4
2
5
Converting....
Invalid Parameter - 1x20
Exception in thread "main" javax.imageio.IIOException: Can't read input file!
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1308)
        at dev.t1c.dumpy.sus.main(sus.java:254)
```
I have ImageMagick-7.1.0-2-Q16-x64-static installed, And the imagemagik cli works.

**Comment by ThatOneCalculator** [comment]
You need to have ImageMagick static (the one linked in the readme) installed. The version should be 6.9.x

**Comment by ThatOneCalculator** [comment]
I updated the readme with the correct link, sorry about that
