### ISSUE TITLE
Exception in thread "main" javax.imageio.IIOException: Can't read input file!

### ISSUE THREAD

**Issue by AcaiBerii** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#40]
```
Exception in thread "main" javax.imageio.IIOException: Can't read input file!
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1308)
        at dev.t1c.dumpy.sus.main(sus.java:138)
```

**Comment by ThatOneCalculator** [comment]
Either you didn't install ImageMagick correctly (most likely) or messed up the file path. Not a bug.
